server:
  port: 8080

spring:
  application:
    name: bookpoint-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-catalogo
              uri: lb://bookpoint-ms-catalogo
              predicates:
                - Path=/api/v1/catalogo/**
            - id: ms-pedidos
              uri: lb://bookpoint-ms-pedidos
              predicates:
                - Path=/api/v1/pedidos/**
            - id: ms-inventario
              uri: lb://bookpoint-ms-inventario
              predicates:
                - Path=/api/v1/inventario/**
            - id: bookpoint-ms-clientes
              uri: lb://bookpoint-ms-clientes
              predicates:
                - Path=/api/v1/clientes/**
            - id: bookpoint-ms-sucursales
              uri: lb://bookpoint-ms-sucursales
              predicates:
                - Path=/api/v1/sucursales/**
            - id: bookpoint-ms-carrito
              uri: lb://bookpoint-ms-carrito
              predicates:
                - Path=/api/v1/carrito/**
            - id: bookpoint-ms-pagos
              uri: lb://bookpoint-ms-pagos
              predicates:
                - Path=/api/v1/pagos/**
            - id: bookpoint-ms-envios
              uri: lb://bookpoint-ms-envios
              predicates:
                - Path=/api/v1/envios/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/