server:
  port: 8084

spring:
  application:
    name: bookpoint-ms-clientes
  datasource:
    url: jdbc:mysql://localhost:3306/bookpoint_clientes_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/